language: objective-c
osx_image: xcode7.3
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
install: true
script:
  - set -o pipefail
  - xcodebuild test -scheme Tyro -configuration Debug | xcpretty -c
  - xcodebuild test -scheme Tyro-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild build -scheme Tyro-watchOS -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm' | xcpretty -c
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
